sylius_grid:
    grids:
        sylius_admin_customer:
            fields:
                trustpilotEnabled:
                    type: twig
                    label: setono_sylius_trustpilot.ui.trustpilot_enabled
                    sortable: ~
                    path: .
                    options:
                        template: "@SetonoSyliusTrustpilotPlugin/Customer/Grid/Field/trustpilotEnabled.html.twig"
