sylius_grid:
    grids:
        sylius_admin_order:
            fields:
                trustpilotEmailsSent:
                    type: twig
                    label: setono_sylius_trustpilot.ui.trustpilot_emails_sent
                    sortable: ~
                    path: .
                    options:
                        template: "@SetonoSyliusTrustpilotPlugin/Order/Grid/Field/trustpilotEmailsSent.html.twig"
